#!/bin/bash
#
# Things to do before patching Buildroot
#

# Removes packages/files added through patches:
rm -rf buildroot/package/beremiz
rm -rf buildroot/boot/uboot/
rm -rf buildroot/package/quake-pak/
rm -rf buildroot/package/sdlquake/
rm -rf buildroot/package/gpm/
rm -rf buildroot/package/python-pygame/
rm -rf buildroot/package/python-pyro/
rm -rf buildroot/package/uucp/
rm -rf buildroot/package/matiec/
rm -f  buildroot/package/multimedia/libsndfile/libsndfile-1.0.*-srconly.patch
rm -rf buildroot/package/multimedia/flite/
rm -rf buildroot/package/libcurl/
rm -f  buildroot/package/multimedia/mplayer/mplayer-1.0rc2-add_pld_asm_inst_for_non_armv5_arch.patch
rm -f  buildroot/package/multimedia/madplay/madplay-audio-alsa.patch
rm -rf buildroot/package/wolf4sdl/
rm -rf buildroot/package/lmbench/
rm -rf buildroot/package/tslib/
rm -rf buildroot/package/openssh/
rm -rf buildroot/package/qtcreator
rm -rf buildroot/package/sdl/
rm -rf buildroot/package/sdl_water/
rm -rf buildroot/package/slideshow/
rm -rf buildroot/package/python-crc16/
rm -rf buildroot/package/socketcan/
rm -rf buildroot/package/lcd4linux/
rm -rf buildroot/package/mesa/
rm -rf buildroot/package/snes9x/
rm -rf buildroot/package/allegro/
rm -rf buildroot/package/fbgrab/
rm -rf buildroot/package/fbtest/
rm -rf buildroot/package/xenomai/
rm -rf buildroot/package/cwiid/
rm -rf buildroot/package/urg/
rm -rf buildroot/package/pywebradio/
rm -rf buildroot/package/e-uae/
rm -rf buildroot/package/opentyrian/
rm -rf buildroot/package/ipsec-tools/
rm -rf buildroot/package/java/
rm -rf buildroot/package/lbreakout2/
rm -rf buildroot/package/ltris/
rm -rf buildroot/package/qwt/
rm -rf buildroot/fs/ubi/
rm -f buildroot/package/flex/flex-2.5.35-undefine_rpl_malloc_and_realloc.patch
rm -f buildroot/package/ncurses/ncurses-5.7-allows_build_with_old_ncurses_host_installation.patch
rm -rf buildroot/package/mysql_client/
rm -rf buildroot/package/portmap/
rm -rf buildroot/package/bluez3*
rm -rf buildroot/package/ngircd/
rm -rf buildroot/package/can-utils/
rm -f buildroot/toolchain/uClibc/*.patch
rm -f buildroot/package/ntp/ntp-nano.patch
rm -f buildroot/target/generic/Config.in
rm -rf buildroot/package/rt-tests
rm -rf buildroot/package/libcanfestival
rm -rf buildroot/package/python
rm -rf buildroot/package/gsmmux
rm -rf buildroot/package/imx-lib/
rm -rf buildroot/package/imx-test/
rm -rf buildroot/package/e2fsprogs/
rm -rf buildroot/package/firmware-imx/
rm -rf buildroot/package/multimedia/fsl-mm-codeclib/
rm -rf buildroot/package/linux-firmware/
rm -rf buildroot/package/uboot-tools/
rm -rf buildroot/package/qtcreator/
rm -rf buildroot/package/marble/
rm -rf buildroot/package/cunit/
rm -rf buildroot/package/gnokii/
rm -rf buildroot/package/smstools3/
rm -rf buildroot/package/wpa_supplicant/
rm -rf buildroot/package/busybox/
rm -rf buildroot/package/joe/
rm -rf buildroot/package/gpsd/
rm -rf buildroot/linux/
